name: BUILD

on:
  push:
    branches-ignore:
      - master
      - develop
    pull-request: true

jobs:
  cd:
    name: Execute test and analyzes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_versions: ['7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}
        extensions: json

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Lint
      run: find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l > /dev/null

    - name: Run PhpStan
      run: php vendor/bin/phpstan analyse --quiet

    - name: Run Rector
      run: php vendor/bin/rector --dry-run --no-ansi --no-diffs --no-progress-bar

    - name: Run PhpCsFixer
      run: php vendor/bin/php-cs-fixer fix --dry-run -q