name: BUILD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  cd:
    name: Execute test and analyzes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_versions: ['7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}
        extensions: json

    - name: Install dependencies
      run: make install

    - name: Run CD
      run: make cd
